### ISSUE TITLE
Double Artist Slideshow when using SpotiMC (SKIBBE)

### ISSUE THREAD

**Issue by kib** [kib/skin.neon#13]
When running SpotiMC artist slideshow is enabled by default, but you can still enable it under settings in Neon resulting in 2 artist slide show running at the same time.

**Comment by kib** [comment]
@mazkolain, maybe you have a clue how we can solve this ?

**Comment by mazkolain-zz** [comment]
Hello @kibje,

This is strange, since Spotimc does not provide any artist slideshow functionality at all. It does set all the metadata for every track, so plugins providing this feature can read it.

I'll try to test Spotimc with Neon and see what happens. It's fine to test agains the latest version of your repo?

**Comment by kib** [comment]
Yes, at the moment they are synchronised. You can also install Neon from
superrepo.org or passion-xbmc.org repositories

**Comment by mazkolain-zz** [comment]
Hello @kibje,

I did some tests but couldn't experience the double artist slideshow issue.

But, I did notice some differences the way Neon implements artist slideshow compared to other skins. On Quartz for example, the artist slideshow script is invoked on the window's `<onload>` tag:
https://github.com/pecinko/quartz/blob/master/1080i/MusicVisualisation.xml#L5

On Neon this is done on the `<onfocus>` tag of a button control (which could be potentially triggered more than once):
https://github.com/kibje/skin.neon/blob/Frodo/720p/MusicVisualisation.xml#L11

I've looked other implementations and they also follow the first method too. Could this difference have something to do with the issue?

**Comment by kib** [comment]
@mazkolain,

I am pretty sure that is exactly what is happening.
Because people had only noticed this in combination with SpotiMC so far, I thought of asking you.

Looks like I'll have to do some experimenting myself. 
Thx for the assistance !

I'll try out tonight if changing the plugin loading to the onload of the window fixes the issue.

**Comment by kib** [comment]
fixed with https://github.com/kibje/skin.neon/commit/8a2527937a666908395d81a2bb68f88827ff81e8
